name: 04 - Variaveis, Secrets e Environments

on:
  push:
    branches: [main]

# Variáveis disponíveis em todos os jobs
env:
  APP_NAME: minha-api
  NODE_VERSION: "20"

jobs:
  variaveis:
    name: Tipos de variáveis
    runs-on: ubuntu-latest

    # Variável só neste job
    env:
      JOB_VAR: "valor local do job"

    steps:
      - name: Variável global
        run: echo "App: $APP_NAME"

      - name: Variável do job
        run: echo "Job var: $JOB_VAR"

      - name: Secret (valor fica oculto no log)
        run: echo "Token existe? ${{ secrets.GITHUB_TOKEN != '' }}"

      - name: Variável de step
        id: meu-step
        run: echo "resultado=sucesso" >> $GITHUB_OUTPUT

      - name: Usar output do step anterior
        run: echo "Resultado anterior: ${{ steps.meu-step.outputs.resultado }}"

  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment: development          # ambiente configurado no GitHub Settings
    steps:
      - run: echo "Fazendo deploy no DEV..."

  deploy-prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production           # pode exigir aprovação manual
    steps:
      - run: echo "Fazendo deploy em PROD com aprovacao!"
